using System.Globalization;

namespace JarvisAI.Application.Search;

public static class OfficialSiteCatalog
{
    private static readonly Dictionary<string, string> Domains = new(StringComparer.OrdinalIgnoreCase)
    {
        ["discord"] = "discord.com",
        ["firefox"] = "mozilla.org",
        ["samsung"] = "samsung.com",
        ["microsoft"] = "microsoft.com",
        ["github"] = "github.com",
        ["visual studio"] = "visualstudio.microsoft.com",
        ["vs code"] = "code.visualstudio.com",
        ["openai"] = "openai.com",
        ["ollama"] = "ollama.com",
        ["google"] = "google.com",
        ["youtube"] = "youtube.com",
        ["reddit"] = "reddit.com",
        ["wikipedia"] = "wikipedia.org",
        ["stack overflow"] = "stackoverflow.com",
        ["stackoverflow"] = "stackoverflow.com",
        ["nvidia"] = "nvidia.com",
        ["intel"] = "intel.com",
        ["amd"] = "amd.com",
        ["arduino"] = "arduino.cc",
        ["docker"] = "docker.com",
        ["oracle"] = "oracle.com",
        ["brave"] = "brave.com",
        ["duckduckgo"] = "duckduckgo.com",
        ["adobe"] = "adobe.com",
        ["apple"] = "apple.com",
        ["netflix"] = "netflix.com",
        ["spotify"] = "spotify.com",
        ["steam"] = "store.steampowered.com",
        ["blender"] = "blender.org",
        ["jetbrains"] = "jetbrains.com",
        ["epic games"] = "epicgames.com",
        ["amazon"] = "amazon.com",
        ["parcoursup"] = "parcoursup.fr",
        ["onisep"] = "onisep.fr",
        ["l'étudiant"] = "letudiant.fr",
        ["l'etudiant"] = "letudiant.fr",
        ["letudiant"] = "letudiant.fr",
        ["studyrama"] = "studyrama.com",
        ["le monde"] = "lemonde.fr",
        ["lemonde"] = "lemonde.fr",
        ["franceinfo"] = "franceinfo.fr",
        ["france info"] = "franceinfo.fr",
        ["bbc"] = "bbc.com",
        ["the verge"] = "theverge.com",
        ["ars technica"] = "arstechnica.com",
        ["techcrunch"] = "techcrunch.com",
        ["reuters"] = "reuters.com",
        ["afp"] = "afp.com",
        ["linux"] = "kernel.org",
        ["mozilla"] = "mozilla.org",
        ["python"] = "python.org",
        ["rust"] = "rust-lang.org",
        ["java"] = "oracle.com",
        ["kubernetes"] = "kubernetes.io",
        ["react"] = "react.dev",
        ["node.js"] = "nodejs.org",
        ["node"] = "nodejs.org",
        ["postman"] = "postman.com",
        ["figma"] = "figma.com",
        ["notion"] = "notion.so",
        ["slack"] = "slack.com",
        ["zoom"] = "zoom.us",
        ["signal"] = "signal.org",
        ["telegram"] = "telegram.org",
        ["whatsapp"] = "whatsapp.com",
        ["x (twitter)"] = "x.com",
        ["twitter"] = "x.com",
        ["instagram"] = "instagram.com",
        ["facebook"] = "facebook.com",
        ["linkedin"] = "linkedin.com",
        ["tiktok"] = "tiktok.com",
        ["twitch"] = "twitch.tv",
        ["nasa"] = "nasa.gov",
        ["spacex"] = "spacex.com",
        ["tesla"] = "tesla.com",
        ["sony"] = "sony.com",
        ["nintendo"] = "nintendo.com",
        ["playstation"] = "playstation.com",
        ["xbox"] = "xbox.com",
        ["unity"] = "unity.com",
        ["unreal engine"] = "unrealengine.com",
        ["godot"] = "godotengine.org",
        ["gimp"] = "gimp.org",
        ["audacity"] = "audacityteam.org",
        ["obs"] = "obsproject.com",
        ["vim"] = "vim.org",
        ["emacs"] = "gnu.org",
        ["git"] = "git-scm.com",
        ["libreoffice"] = "libreoffice.org",
        ["kdenlive"] = "kdenlive.org",
        ["ffmpeg"] = "ffmpeg.org",
        ["imagemagick"] = "imagemagick.org",
        ["7-zip"] = "7-zip.org",
        ["winrar"] = "rarlab.com",
        ["vlc"] = "videolan.org",
        ["notepad++"] = "notepad-plus-plus.org",
        ["sharpdevelop"] = "github.com",
        ["mono"] = "mono-project.com",
        [".net"] = "dotnet.microsoft.com",
        ["dotnet"] = "dotnet.microsoft.com",
        ["nuget"] = "nuget.org",
        ["visual studio code"] = "code.visualstudio.com",
        ["azure"] = "azure.microsoft.com",
        ["windows"] = "microsoft.com",
        ["office"] = "microsoft.com",
        ["excel"] = "microsoft.com",
        ["word"] = "microsoft.com",
        ["powerpoint"] = "microsoft.com",
        ["google maps"] = "maps.google.com",
        ["gmail"] = "gmail.com",
        ["chrome"] = "google.com",
        ["safari"] = "apple.com",
        ["edge"] = "microsoft.com",
        ["opera"] = "opera.com",
        ["vivaldi"] = "vivaldi.com",
        ["tor"] = "torproject.org",
        ["protonmail"] = "proton.me",
        ["notion.so"] = "notion.so",
        ["mongodb"] = "mongodb.com",
        ["mysql"] = "mysql.com",
        ["postgresql"] = "postgresql.org",
        ["sqlite"] = "sqlite.org",
        ["redis"] = "redis.io",
        ["elastic"] = "elastic.co",
        ["kibana"] = "elastic.co",
        ["grafana"] = "grafana.com",
        ["jenkins"] = "jenkins.io",
        ["ansible"] = "ansible.com",
        ["terraform"] = "terraform.io",
        ["vagrant"] = "vagrantup.com",
        ["packer"] = "packer.io",
        ["prometheus"] = "prometheus.io",
        ["consul"] = "consul.io",
        ["vault"] = "vaultproject.io",
        ["hashicorp"] = "hashicorp.com",
        ["gitlab"] = "gitlab.com",
        ["bitbucket"] = "bitbucket.org",
        ["sourceforge"] = "sourceforge.net",
        ["codeplex"] = "archive.codeplex.com",
        ["coursera"] = "coursera.org",
        ["udemy"] = "udemy.com",
        ["codecademy"] = "codecademy.com",
        ["khan academy"] = "khanacademy.org",
        ["w3schools"] = "w3schools.com",
        ["mozilla developer"] = "developer.mozilla.org",
        ["mdn"] = "developer.mozilla.org",
        ["learn.microsoft.com"] = "learn.microsoft.com",
        ["learn microsoft"] = "learn.microsoft.com",
        ["microsoft learn"] = "learn.microsoft.com",
        ["docs.python.org"] = "docs.python.org",
        ["python doc"] = "docs.python.org",
        ["nvidia developer"] = "developer.nvidia.com",
        ["nvidia docs"] = "docs.nvidia.com",
        ["cuda"] = "developer.nvidia.com",
        ["openai api"] = "platform.openai.com",
        ["playwright"] = "playwright.dev",
        ["puppeteer"] = "pptr.dev",
        ["selenium"] = "selenium.dev",
        ["cypress"] = "cypress.io",
        ["jest"] = "jestjs.io",
        ["mocha"] = "mochajs.org",
        ["babel"] = "babeljs.io",
        ["webpack"] = "webpack.js.org",
        ["vite"] = "vitejs.dev",
        ["next.js"] = "nextjs.org",
        ["nuxt"] = "nuxt.com",
        ["astro"] = "astro.build",
        ["svelte"] = "svelte.dev",
        ["vue"] = "vuejs.org",
        ["angular"] = "angular.dev",
        ["flutter"] = "flutter.dev",
        ["react native"] = "reactnative.dev",
        ["xamarin"] = "dotnet.microsoft.com",
        ["electron"] = "electronjs.org",
        ["tauri"] = "tauri.app",
        ["sass"] = "sass-lang.com",
        ["less"] = "lesscss.org",
        ["tailwind"] = "tailwindcss.com",
        ["bootstrap"] = "getbootstrap.com",
        ["material ui"] = "mui.com",
        ["chakra"] = "chakra-ui.com",
        ["storybook"] = "storybook.js.org",
        ["graphql"] = "graphql.org",
        ["apollo"] = "apollographql.com",
        ["rest"] = "restfulapi.net",
        ["grpc"] = "grpc.io",
        ["rabbitmq"] = "rabbitmq.com",
        ["kafka"] = "kafka.apache.org",
        ["zeromq"] = "zeromq.org",
        ["hadoop"] = "hadoop.apache.org",
        ["spark"] = "spark.apache.org",
        ["flink"] = "flink.apache.org",
        ["airflow"] = "airflow.apache.org",
        ["dask"] = "dask.org",
        ["jupyter"] = "jupyter.org",
        ["pandas"] = "pandas.pydata.org",
        ["numpy"] = "numpy.org",
        ["scipy"] = "scipy.org",
        ["scikit-learn"] = "scikit-learn.org",
        ["tensorflow"] = "tensorflow.org",
        ["pytorch"] = "pytorch.org",
        ["keras"] = "keras.io",
        ["hugging face"] = "huggingface.co",
        ["transformers"] = "huggingface.co",
        ["opencv"] = "opencv.org",
        ["qt"] = "qt.io",
        ["kde"] = "kde.org",
        ["gnome"] = "gnome.org",
        ["xfce"] = "xfce.org",
        ["apache"] = "apache.org",
        ["nginx"] = "nginx.org",
        ["caddy"] = "caddyserver.com",
        ["haproxy"] = "haproxy.org",
        ["iis"] = "microsoft.com",
        ["wordpress"] = "wordpress.org",
        ["joomla"] = "joomla.org",
        ["drupal"] = "drupal.org",
        ["ghost"] = "ghost.org",
        ["medium"] = "medium.com",
        ["substack"] = "substack.com",
        ["discourse"] = "discourse.org",
        ["phpbb"] = "phpbb.com",
        ["moodle"] = "moodle.org",
        ["canvas"] = "instructure.com",
        ["blackboard"] = "blackboard.com",
        ["zotero"] = "zotero.org",
        ["mendeley"] = "mendeley.com",
        ["overleaf"] = "overleaf.com",
        ["latex"] = "latex-project.org",
        ["texstudio"] = "texstudio.org",
        ["winamp"] = "winamp.com",
        ["foobar2000"] = "foobar2000.org",
        ["audirvana"] = "audirvana.com",
        ["plex"] = "plex.tv",
        ["kodi"] = "kodi.tv",
        ["jellyfin"] = "jellyfin.org",
        ["emby"] = "emby.media",
        ["home assistant"] = "home-assistant.io",
        ["homebridge"] = "homebridge.io",
        ["hass"] = "home-assistant.io",
        ["raspberry pi"] = "raspberrypi.com",
        ["raspberrypi"] = "raspberrypi.com",
        ["adafruit"] = "adafruit.com",
        ["sparkfun"] = "sparkfun.com",
        ["digikey"] = "digikey.com",
        ["mouser"] = "mouser.com",
        ["aliyun"] = "aliyun.com",
        ["cloudflare"] = "cloudflare.com",
        ["aws"] = "aws.amazon.com",
        ["amazon web services"] = "aws.amazon.com",
        ["gcp"] = "cloud.google.com",
        ["google cloud"] = "cloud.google.com",
        ["ibm cloud"] = "cloud.ibm.com",
        ["vultr"] = "vultr.com",
        ["digitalocean"] = "digitalocean.com",
        ["linode"] = "linode.com",
        ["hetzner"] = "hetzner.com",
        ["ovh"] = "ovh.com",
        ["scaleway"] = "scaleway.com",
        ["render"] = "render.com",
        ["vercel"] = "vercel.com",
        ["netlify"] = "netlify.com",
        ["github pages"] = "pages.github.com",
        ["gitlab pages"] = "pages.gitlab.io",
        ["firebase"] = "firebase.google.com",
        ["supabase"] = "supabase.com",
        ["heroku"] = "heroku.com",
        ["fly.io"] = "fly.io",
        ["railway"] = "railway.app",
        ["replit"] = "replit.com",
        ["glitch"] = "glitch.com",
        ["codepen"] = "codepen.io",
        ["jsfiddle"] = "jsfiddle.net",
        ["stackblitz"] = "stackblitz.com",
        ["codesandbox"] = "codesandbox.io",
        ["github copilot"] = "github.com",
        ["chatgpt"] = "chatgpt.com",
        ["claude"] = "anthropic.com",
        ["anthropic"] = "anthropic.com",
        ["gemini"] = "gemini.google.com",
        ["bard"] = "gemini.google.com",
        ["perplexity"] = "perplexity.ai",
        ["mistral"] = "mistral.ai",
        ["llama"] = "ai.meta.com",
        ["meta"] = "meta.com",
        ["deepseek"] = "deepseek.com",
        ["qwen"] = "qwen.ai",
        ["kimi"] = "kimi.moonshot.cn",
        ["grok"] = "grok.com",
        ["xai"] = "x.ai",
        ["cohere"] = "cohere.com",
        ["together"] = "together.ai",
        ["replicate"] = "replicate.com",
        ["runway"] = "runwayml.com",
        ["midjourney"] = "midjourney.com",
        ["stable diffusion"] = "stability.ai",
        ["stability"] = "stability.ai",
        ["elevenlabs"] = "elevenlabs.io",
        ["whisper"] = "github.com",
        ["tesseract"] = "github.com",
        ["ollama docs"] = "docs.ollama.com"
    };

    private static readonly Dictionary<string, string> OfficialRepos = new(StringComparer.OrdinalIgnoreCase)
    {
        ["ollama"] = "ollama/ollama",
        ["openai"] = "openai/openai-python",
        ["openai api"] = "openai/openai-python",
        ["microsoft"] = "microsoft/vscode",
        ["vs code"] = "microsoft/vscode",
        ["visual studio code"] = "microsoft/vscode",
        ["docker"] = "docker/docker",
        ["linux"] = "torvalds/linux",
        ["rust"] = "rust-lang/rust",
        ["kubernetes"] = "kubernetes/kubernetes",
        ["node"] = "nodejs/node",
        ["python"] = "python/cpython",
        ["llama"] = "meta-llama/llama-models",
        ["qwen"] = "QwenLM/Qwen3",
        ["deepseek"] = "deepseek-ai/DeepSeek-V3",
        ["microsoft semantic kernel"] = "microsoft/semantic-kernel",
        ["dotnet"] = "dotnet/runtime",
        [".net"] = "dotnet/runtime",
        ["asp.net core"] = "dotnet/aspnetcore",
        ["entity framework"] = "dotnet/efcore",
        ["playwright"] = "microsoft/playwright",
        ["puppeteer"] = "puppeteer/puppeteer",
        ["tesseract"] = "tesseract-ocr/tesseract",
        ["whisper"] = "openai/whisper",
        ["ffmpeg"] = "FFmpeg/FFmpeg",
        ["imagemagick"] = "ImageMagick/ImageMagick",
        ["opencv"] = "opencv/opencv",
        ["tensorflow"] = "tensorflow/tensorflow",
        ["pytorch"] = "pytorch/pytorch",
        ["keras"] = "keras-team/keras",
        ["hugging face"] = "huggingface/transformers",
        ["transformers"] = "huggingface/transformers",
        ["pandas"] = "pandas-dev/pandas",
        ["numpy"] = "numpy/numpy",
        ["scipy"] = "scipy/scipy",
        ["scikit-learn"] = "scikit-learn/scikit-learn",
        ["git"] = "git/git",
        ["gitlab"] = "gitlabhq/gitlabhq",
        ["react"] = "facebook/react",
        ["react native"] = "facebook/react-native",
        ["next.js"] = "vercel/next.js",
        ["vue"] = "vuejs/core",
        ["svelte"] = "sveltejs/svelte",
        ["angular"] = "angular/angular",
        ["flutter"] = "flutter/flutter",
        ["electron"] = "electron/electron",
        ["tauri"] = "tauri-apps/tauri",
        ["vite"] = "vitejs/vite",
        ["webpack"] = "webpack/webpack",
        ["jest"] = "jestjs/jest",
        ["babel"] = "babel/babel",
        ["mocha"] = "mochajs/mocha",
        ["cypress"] = "cypress-io/cypress",
        ["selenium"] = "SeleniumHQ/selenium",
        ["graphql"] = "graphql/graphql-js",
        ["apollo"] = "apollographql/apollo-client",
        ["kafka"] = "apache/kafka",
        ["spark"] = "apache/spark",
        ["hadoop"] = "apache/hadoop",
        ["flink"] = "apache/flink",
        ["airflow"] = "apache/airflow",
        ["rabbitmq"] = "rabbitmq/rabbitmq-server",
        ["redis"] = "redis/redis",
        ["mongodb"] = "mongodb/mongo",
        ["mysql"] = "mysql/mysql-server",
        ["postgresql"] = "postgres/postgres",
        ["sqlite"] = "sqlite/sqlite",
        ["ansible"] = "ansible/ansible",
        ["terraform"] = "hashicorp/terraform",
        ["vagrant"] = "hashicorp/vagrant",
        ["vault"] = "hashicorp/vault",
        ["consul"] = "hashicorp/consul",
        ["prometheus"] = "prometheus/prometheus",
        ["grafana"] = "grafana/grafana",
        ["jenkins"] = "jenkinsci/jenkins",
        ["elasticsearch"] = "elastic/elasticsearch",
        ["logstash"] = "elastic/logstash",
        ["kibana"] = "elastic/kibana",
        ["nginx"] = "nginx/nginx",
        ["caddy"] = "caddyserver/caddy",
        ["haproxy"] = "haproxy/haproxy",
        ["wordpress"] = "WordPress/wordpress-develop",
        ["drupal"] = "drupal/drupal",
        ["joomla"] = "joomla/joomla-cms",
        ["moodle"] = "moodle/moodle",
        ["tor"] = "torproject/tor",
        ["blender"] = "blender/blender",
        ["godot"] = "godotengine/godot",
        ["gimp"] = "GNOME/gimp",
        ["libreoffice"] = "LibreOffice/core",
        ["kdenlive"] = "KDE/kdenlive",
        ["vlc"] = "videolan/vlc",
        ["obs"] = "obsproject/obs-studio",
        ["audacity"] = "audacity/audacity",
        ["notepad++"] = "notepad-plus-plus/notepad-plus-plus",
        ["sharpdevelop"] = "icsharpcode/SharpDevelop",
        ["mono"] = "mono/mono",
        ["nuget"] = "NuGet/NuGet.Client",
        ["home assistant"] = "home-assistant/core",
        ["jellyfin"] = "jellyfin/jellyfin",
        ["plex"] = "plexinc/plex-media-server",
        ["kodi"] = "xbmc/xbmc",
        ["syncthing"] = "syncthing/syncthing",
        ["duckdb"] = "duckdb/duckdb",
        ["rocksdb"] = "facebook/rocksdb",
        ["leveldb"] = "google/leveldb",
        ["etcd"] = "etcd-io/etcd",
        ["zookeeper"] = "apache/zookeeper",
        ["cassandra"] = "apache/cassandra",
        ["hbase"] = "apache/hbase",
        ["kafka"] = "apache/kafka",
        ["flink"] = "apache/flink",
        ["storm"] = "apache/storm",
        ["solr"] = "apache/solr",
        ["lucene"] = "apache/lucene",
        ["espresso"] = "apache/accumulo",
        ["accumulo"] = "apache/accumulo",
        ["drill"] = "apache/drill",
        ["tez"] = "apache/tez",
        ["storm"] = "apache/storm",
        ["giraph"] = "apache/giraph",
        ["openjdk"] = "openjdk/jdk",
        ["jdk"] = "openjdk/jdk",
        ["graalvm"] = "oracle/graal",
        ["coco"] = "pytorch/vision",
        ["yolo"] = "ultralytics/ultralytics",
        ["detectron2"] = "facebookresearch/detectron2",
        ["fastai"] = "fastai/fastai",
        ["jax"] = "google/jax",
        ["flax"] = "google/flax",
        ["lightgbm"] = "microsoft/LightGBM",
        ["xgboost"] = "dmlc/xgboost",
        ["catboost"] = "catboost/catboost",
        ["sentence-transformers"] = "UKPLab/sentence-transformers",
        ["sbert"] = "UKPLab/sentence-transformers",
        ["chromadb"] = "chroma-core/chroma",
        ["weaviate"] = "weaviate/weaviate",
        ["pinecone"] = "pinecone-io/pinecone-ts-client",
        ["qdrant"] = "qdrant/qdrant",
        ["milvus"] = "milvus-io/milvus",
        ["langchain"] = "langchain-ai/langchain",
        ["langgraph"] = "langchain-ai/langgraph",
        ["llamaindex"] = "run-llama/llama_index",
        ["autogen"] = "microsoft/autogen",
        ["semantic kernel"] = "microsoft/semantic-kernel",
        ["jarvis"] = "aburke224/Jarvis",
        ["ollama dotnet"] = "ollama/ollama-dotnet",
        // LLM locaux / outils populaires
        ["llama.cpp"] = "ggerganov/llama.cpp",
        ["whisper.cpp"] = "ggerganov/whisper.cpp",
        ["ggml"] = "ggerganov/ggml",
        ["piper"] = "rhasspy/piper",
        ["comfyui"] = "comfyanonymous/ComfyUI",
        ["text-generation-webui"] = "oobabooga/text-generation-webui",
        ["axolotl"] = "axolotl-ai-cloud/axolotl",
        ["unsloth"] = "unslothai/unsloth",
        ["fastchat"] = "lm-sys/FastChat",
        ["vllm"] = "vllm-project/vllm",
        ["ollama python"] = "ollama/ollama-python",
        ["litellm"] = "BerriAI/litellm",
        ["open-webui"] = "open-webui/open-webui",
        ["dify"] = "langgenius/dify",
        ["flowise"] = "FlowiseAI/Flowise",
        ["langflow"] = "logspace-ai/langflow",
    };

    private static readonly Dictionary<string, string> OfficialChannels = new(StringComparer.OrdinalIgnoreCase)
    {
        ["mrbeast"] = "https://www.youtube.com/@MrBeast",
        ["mr beast"] = "https://www.youtube.com/@MrBeast",
        ["markiplier"] = "https://www.youtube.com/@markiplier",
        ["pewdiepie"] = "https://www.youtube.com/@PewDiePie",
        ["game theory"] = "https://www.youtube.com/@GameTheory",
        ["matpat"] = "https://www.youtube.com/@GameTheory",
        ["veritasium"] = "https://www.youtube.com/@veritasium",
        ["3blue1brown"] = "https://www.youtube.com/@3blue1brown",
        ["3b1b"] = "https://www.youtube.com/@3blue1brown",
        ["kurzgesagt"] = "https://www.youtube.com/@kurzgesagt",
        ["technology connections"] = "https://www.youtube.com/@TechnologyConnections",
        ["linus tech tips"] = "https://www.youtube.com/@LinusTechTips",
        ["ltt"] = "https://www.youtube.com/@LinusTechTips",
        ["mrzollocoin"] = "https://www.youtube.com/@MrZollocoin",
        ["megaauto"] = "https://www.youtube.com/@MegaAuto",
        ["squid game"] = "https://www.youtube.com/@Netflix",
        ["netflix"] = "https://www.youtube.com/@Netflix",
        ["faster than light"] = "https://www.youtube.com/@kurzgesagt",
        // Marques constructeurs (officiel)
        ["apple"] = "https://www.youtube.com/@Apple",
        ["google"] = "https://www.youtube.com/@Google",
        ["microsoft"] = "https://www.youtube.com/@Microsoft",
        ["samsung"] = "https://www.youtube.com/@Samsung",
        ["sony"] = "https://www.youtube.com/@Sony",
        ["nintendo"] = "https://www.youtube.com/@Nintendo",
        ["playstation"] = "https://www.youtube.com/@PlayStation",
        ["xbox"] = "https://www.youtube.com/@Xbox",
        ["intel"] = "https://www.youtube.com/@Intel",
        ["nvidia"] = "https://www.youtube.com/@NVIDIAAIDev",
        ["amd"] = "https://www.youtube.com/@AMD",
        ["tesla"] = "https://www.youtube.com/@Tesla",
        ["bmw"] = "https://www.youtube.com/@BMW",
        ["mercedes"] = "https://www.youtube.com/@MercedesBenz",
        ["audi"] = "https://www.youtube.com/@Audi",
        ["toyota"] = "https://www.youtube.com/@ToyotaUSA",
        ["honda"] = "https://www.youtube.com/@Honda",
        ["volvo"] = "https://www.youtube.com/@VolvoCarGroup",
        ["spacex"] = "https://www.youtube.com/@SpaceX",
        ["nasa"] = "https://www.youtube.com/@NASA",
        ["huawei"] = "https://www.youtube.com/@Huawei",
        ["xiaomi"] = "https://www.youtube.com/@XiaomiGlobal",
        ["oppo"] = "https://www.youtube.com/@OPPO",
        ["oneplus"] = "https://www.youtube.com/@OnePlus",
        // IA / dev
        ["openai"] = "https://www.youtube.com/@OpenAI",
        ["anthropic"] = "https://www.youtube.com/@AnthropicAI",
        ["deepmind"] = "https://www.youtube.com/@GoogleDeepMind",
        ["huggingface"] = "https://www.youtube.com/@HuggingFace",
        // Tech / revue / presse
        ["the verge"] = "https://www.youtube.com/@TheVerge",
        ["mkbhd"] = "https://www.youtube.com/@MKBHD",
        ["marques brownlee"] = "https://www.youtube.com/@MKBHD",
        ["dave2d"] = "https://www.youtube.com/@Dave2D",
        ["unbox therapy"] = "https://www.youtube.com/@UnboxTherapy",
        ["mrwhosetheboss"] = "https://www.youtube.com/@Mrwhosetheboss",
        ["jerryrigeverything"] = "https://www.youtube.com/@JerryRigEverything",
        ["ijustine"] = "https://www.youtube.com/@iJustine",
        ["fireship"] = "https://www.youtube.com/@Fireship",
        ["two minute papers"] = "https://www.youtube.com/@TwoMinutePapers",
        ["yannic kilcher"] = "https://www.youtube.com/@YannicKilcher",
        ["sentdex"] = "https://www.youtube.com/@sentdex",
        ["the coding train"] = "https://www.youtube.com/@TheCodingTrain",
        ["tom scott"] = "https://www.youtube.com/@TomScottGo",
        ["lex fridman"] = "https://www.youtube.com/@lexfridman",
        ["huberman"] = "https://www.youtube.com/@hubermanlab",
        ["vsauce"] = "https://www.youtube.com/@Vsauce",
        // FR
        ["france inter"] = "https://www.youtube.com/@franceinter",
        ["bfmtv"] = "https://www.youtube.com/@BFMTV",
        ["france 24"] = "https://www.youtube.com/@FRANCE24",
    };

    private static readonly Dictionary<string, string> Schools = new(StringComparer.OrdinalIgnoreCase)
    {
        ["parcoursup"] = "https://www.parcoursup.fr",
        ["onisep"] = "https://www.onisep.fr",
        ["l'étudiant"] = "https://www.letudiant.fr",
        ["studyrama"] = "https://www.studyrama.com",
        ["crous"] = "https://www.crous.fr",
        ["académie de bordeaux"] = "https://www.ac-bordeaux.fr",
        ["académie de paris"] = "https://www.ac-paris.fr",
        ["académie de lyon"] = "https://www.ac-lyon.fr",
        ["académie de nantes"] = "https://www.ac-nantes.fr",
        ["académie de toulouse"] = "https://www.ac-toulouse.fr",
        ["académie de lille"] = "https://www.ac-lille.fr",
        ["académie de strasbourg"] = "https://www.ac-strasbourg.fr",
        ["académie de reims"] = "https://www.ac-reims.fr",
        ["académie de nice"] = "https://www.ac-nice.fr",
        ["académie de marseille"] = "https://www.ac-aix-marseille.fr",
        ["académie de rouen"] = "https://www.ac-rouen.fr",
        ["académie de poitiers"] = "https://www.ac-poitiers.fr",
        ["académie de orléans"] = "https://www.ac-orleans-tours.fr",
        ["académie de besançon"] = "https://www.ac-besancon.fr",
        ["académie de dijon"] = "https://www.ac-dijon.fr",
        ["académie de clermont"] = "https://www.ac-clermont.fr",
        ["académie de grenoble"] = "https://www.ac-grenoble.fr",
        ["académie de la réunion"] = "https://www.ac-reunion.fr",
        ["académie de guadeloupe"] = "https://www.ac-guadeloupe.fr",
        ["académie de martinique"] = "https://www.ac-martinique.fr",
        ["académie de guyane"] = "https://www.ac-guyane.fr",
        ["académie de corse"] = "https://www.ac-corse.fr",
        ["académie de limoges"] = "https://www.ac-limoges.fr",
        ["académie de caen"] = "https://www.ac-caen.fr",
        ["académie de montpellier"] = "https://www.ac-montpellier.fr",
        ["académie d'amiens"] = "https://www.ac-amiens.fr",
        // Grandes écoles d'ingénieurs
        ["polytechnique"] = "https://www.polytechnique.edu",
        ["ecole polytechnique"] = "https://www.polytechnique.edu",
        ["centrale supélec"] = "https://www.centralesupelec.fr",
        ["centrale paris"] = "https://www.ecp.fr",
        ["centrale lyon"] = "https://www.ec-lyon.fr",
        ["centrale lille"] = "https://www.centralelille.fr",
        ["centrale nantes"] = "https://www.ec-nantes.fr",
        ["mines paris"] = "https://www.minesparis.psl.eu",
        ["mines saint-etienne"] = "https://www.mines-stetienne.fr",
        ["mines nantes"] = "https://www.imt-atlantique.fr",
        ["insa"] = "https://www.insa-toulouse.fr",
        ["insa toulouse"] = "https://www.insa-toulouse.fr",
        ["insa lyon"] = "https://www.insa-lyon.fr",
        ["insa rennes"] = "https://www.insa-rennes.fr",
        ["insa rouen"] = "https://www.insa-rouen.fr",
        ["ens paris-saclay"] = "https://www.ens-paris-saclay.fr",
        ["ens lyon"] = "https://www.ens-lyon.fr",
        ["ens ulm"] = "https://www.ens.fr",
        ["ensae"] = "https://www.ensae.fr",
        ["ensta"] = "https://www.ensta-paris.fr",
        ["ensta paris"] = "https://www.ensta-paris.fr",
        ["ensea"] = "https://www.ensea.fr",
        ["enseeiht"] = "https://www.enseeiht.fr",
        ["utc compiègne"] = "https://www.utc.fr",
        ["utc"] = "https://www.utc.fr",
        ["utbm"] = "https://www.utbm.fr",
        ["utt"] = "https://www.utt.fr",
        ["enseirb"] = "https://www.enseirb-matmeca.fr",
        ["agrosup"] = "https://www.institut-agro.fr",
        // Écoles de commerce
        ["hec"] = "https://www.hec.edu",
        ["hec paris"] = "https://www.hec.edu",
        ["essec"] = "https://www.essec.edu",
        ["em lyon"] = "https://www.em-lyon.com",
        ["edhec"] = "https://www.edhec.edu",
        ["escp"] = "https://escp.eu",
        ["sciences po"] = "https://www.sciencespo.fr",
        ["sciences po paris"] = "https://www.sciencespo.fr",
        ["kedge"] = "https://www.kedge.edu",
        ["neoma"] = "https://www.neoma-bs.fr",
        ["skema"] = "https://www.skema.edu",
        ["audencia"] = "https://www.audencia.com",
        ["ieseg"] = "https://www.ieseg.fr",
        ["tbs"] = "https://www.tbs-education.fr",
        ["em normandie"] = "https://www.em-normandie.com",
        // CPGE / prépas intégrées
        ["cpge"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Classes-preparatoires",
        ["prépa"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Classes-preparatoires",
        ["prépa intégrée"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Cycle-integre",
        ["sti2d"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Classes-preparatoires",
        ["cpge intégrée"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Cycle-integre",
        ["école d'ingénieurs"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Ecoles-d-ingenieurs",
        ["école d'ingénieur"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Ecoles-d-ingenieurs",
        ["école de commerce"] = "https://www.onisep.fr/Formation/Enseignement-superieur/Ecoles-de-commerce-et-de-gestion",
    };

    public static IEnumerable<string> DomainKeys => Domains.Keys;
    public static IEnumerable<string> RepoKeys => OfficialRepos.Keys;
    public static IEnumerable<string> ChannelKeys => OfficialChannels.Keys;
    public static IEnumerable<string> SchoolKeys => Schools.Keys;
    public static IReadOnlyList<string> AllDomains { get; } = Domains.Values.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
    public static IEnumerable<string> AllMediaDomains => MediaDomains;

    private static readonly HashSet<string> MediaDomains = new(StringComparer.OrdinalIgnoreCase)
    {
        "lemonde.fr", "lefigaro.fr", "franceinfo.fr", "france24.com", "liberation.fr",
        "lesechos.fr", "leparisien.fr", "ladepeche.fr", "sudouest.fr", "ouest-france.fr",
        "20minutes.fr", "lci.fr", "bfmtv.com", "rtl.fr", "europe1.fr", "rfi.fr",
        "nytimes.com", "bbc.com", "bbc.co.uk", "theguardian.com", "washingtonpost.com",
        "reuters.com", "afp.com", "apnews.com", "bloomberg.com", "cnn.com", "npr.org",
        "theverge.com", "arstechnica.com", "techcrunch.com", "wired.com", "engadget.com",
        "gizmodo.com", "pcmag.com", "zdnet.com", "cnet.com", "venturebeat.com",
        "ign.com", "polygon.com", "kotaku.com", "eurogamer.net", "jeuxvideo.com",
        "numama.com", "numerama.com", "frandroid.com", "01net.com", "clubic.com"
    };

    private static readonly Dictionary<string, string> DocsDomains = new(StringComparer.OrdinalIgnoreCase)
    {
        ["langchain"] = "https://docs.langchain.com",
        ["langgraph"] = "https://langchain-ai.github.io/langgraph",
        ["ollama"] = "https://docs.ollama.com",
        ["python"] = "https://docs.python.org",
        ["react"] = "https://react.dev",
        ["next.js"] = "https://nextjs.org/docs",
        ["microsoft learn"] = "https://learn.microsoft.com",
        [".net"] = "https://learn.microsoft.com/dotnet",
        ["dotnet"] = "https://learn.microsoft.com/dotnet",
        ["node"] = "https://nodejs.org/docs",
        ["docker"] = "https://docs.docker.com",
        ["kubernetes"] = "https://kubernetes.io/docs",
        ["tensorflow"] = "https://www.tensorflow.org",
        ["pytorch"] = "https://pytorch.org/docs",
        ["mozilla"] = "https://developer.mozilla.org",
        ["mdn"] = "https://developer.mozilla.org",
        ["git"] = "https://git-scm.com/doc",
        ["linux"] = "https://www.kernel.org/doc",
        ["postgresql"] = "https://www.postgresql.org/docs",
        ["redis"] = "https://redis.io/docs"
    };

    public static bool TryGetOfficialDocsUrl(string entity, out string url)
        => DocsDomains.TryGetValue(entity.Trim(), out url!);

    public static bool IsMediaDomain(string host)
    {
        if (string.IsNullOrWhiteSpace(host))
            return false;
        var h = host.ToLowerInvariant();
        if (h.StartsWith("www.", StringComparison.Ordinal))
            h = h[4..];
        return MediaDomains.Contains(h);
    }

    public static string? FindMediaDomain(string host)
    {
        if (string.IsNullOrWhiteSpace(host))
            return null;
        var h = host.ToLowerInvariant();
        if (h.StartsWith("www.", StringComparison.Ordinal))
            h = h[4..];
        return MediaDomains.FirstOrDefault(m => OfficialSiteCatalog.HostMatchesDomain(h, m) == m);
    }

    public static bool IsDocsHost(string host)
    {
        if (string.IsNullOrWhiteSpace(host))
            return false;
        var h = host.ToLowerInvariant();
        return h.StartsWith("docs.", StringComparison.Ordinal) ||
               h == "learn.microsoft.com" ||
               h.EndsWith(".readthedocs.io", StringComparison.Ordinal) ||
               h.EndsWith(".github.io", StringComparison.Ordinal);
    }

    public static bool TryGetOfficialDomain(string entity, out string domain)
        => Domains.TryGetValue(entity.Trim(), out domain!);

    public static bool TryGetOfficialRepo(string entity, out string repo)
        => OfficialRepos.TryGetValue(entity.Trim(), out repo!);

    public static bool TryGetOfficialChannel(string entity, out string url)
        => OfficialChannels.TryGetValue(entity.Trim(), out url!);

    public static bool TryGetSchoolUrl(string entity, out string url)
        => Schools.TryGetValue(entity.Trim(), out url!);

    public static string NormalizeKey(string value)
        => value.Trim().ToLowerInvariant();

    public static string HostMatchesDomain(string host, string domain)
    {
        if (string.IsNullOrWhiteSpace(host) || string.IsNullOrWhiteSpace(domain))
            return string.Empty;
        var h = host.ToLowerInvariant();
        var d = domain.ToLowerInvariant();
        if (h == d)
            return d;
        if (h.EndsWith("." + d, StringComparison.OrdinalIgnoreCase))
            return d;
        return string.Empty;
    }
}
