using JarvisAI.Application.AI;
using JarvisAI.Application.Memory;
using JarvisAI.Application.Security;
using Microsoft.Extensions.Logging;

namespace JarvisAI.Web.Services;

/// <summary>
/// High-level session operations: create/append/title conversations. Titles are
/// generated by the LLM from the first user message and re-generated only when a
/// completely new topic is detected (embedding cosine similarity below a threshold).
/// </summary>
public sealed class ConversationSessionService
{
    private readonly ConversationSessionStore _store;
    private readonly Lazy<IAIService> _aiService;
    private readonly Lazy<IEmbeddingService> _embeddings;
    private readonly ILogger<ConversationSessionService> _logger;
    private readonly SemaphoreSlim _titleGate = new(1, 1);

    private const float TopicChangeThreshold = 0.35f;
    private const string DefaultTitle = "Nouvelle conversation";

    public event Action? Changed;

    public ConversationSessionService(
        ConversationSessionStore store,
        Lazy<IAIService> aiService,
        Lazy<IEmbeddingService> embeddings,
        ILogger<ConversationSessionService> logger)
    {
        _store = store;
        _aiService = aiService;
        _embeddings = embeddings;
        _logger = logger;
        _store.Changed += () => Changed?.Invoke();
    }

    public IReadOnlyList<ConversationSession> GetSessions(string source, string? search = null, int limit = 100)
    {
        var query = _store.GetAll().Where(s => string.Equals(s.Source, source, StringComparison.OrdinalIgnoreCase));
        if (!string.IsNullOrWhiteSpace(search))
        {
            query = query.Where(s =>
                s.Title.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                s.Messages.Any(m => m.Text.Contains(search, StringComparison.OrdinalIgnoreCase)));
        }
        return query.OrderByDescending(s => s.UpdatedAt).Take(limit).ToList();
    }

    public ConversationSession? GetById(string id) => _store.GetById(id);

    public ConversationSession CreateSession(string source) => _store.Create(source);

    public void AppendMessage(string id, string role, string text, string model = "")
    {
        if (string.IsNullOrWhiteSpace(text)) return;
        _store.Update(id, s => s.Messages.Add(new SessionMessage { Role = role, Text = text, Model = model }));
    }

    public void ReplaceLastUserMessage(string id, string text)
    {
        _store.Update(id, s =>
        {
            for (var i = s.Messages.Count - 1; i >= 0; i--)
            {
                if (string.Equals(s.Messages[i].Role, "user", StringComparison.OrdinalIgnoreCase))
                {
                    s.Messages[i].Text = text;
                    return;
                }
            }
        });
    }

    public void TruncateAfterLastUser(string id)
    {
        _store.Update(id, s =>
        {
            for (var i = s.Messages.Count - 1; i >= 0; i--)
            {
                if (string.Equals(s.Messages[i].Role, "user", StringComparison.OrdinalIgnoreCase))
                {
                    if (s.Messages.Count > i + 1)
                        s.Messages.RemoveRange(i + 1, s.Messages.Count - i - 1);
                    return;
                }
            }
        });
    }

    public void SetModel(string id, string model)
    {
        if (string.IsNullOrWhiteSpace(model)) return;
        _store.Update(id, s => s.Model = model);
    }

    public bool Delete(string id) => _store.Delete(id);

    public void Clear(string source) => _store.Clear(source);

    /// <summary>Titles the session from its first user message if it still has no title.</summary>
    public Task EnsureTitleAsync(string id, string? fallbackText = null, CancellationToken ct = default)
        => SafeAsync(async () =>
        {
            var session = _store.GetById(id);
            if (session is null || session.Title != DefaultTitle) return;

            var firstUser = session.Messages.FirstOrDefault(m => string.Equals(m.Role, "user", StringComparison.OrdinalIgnoreCase))?.Text;
            var sourceText = string.IsNullOrWhiteSpace(firstUser) ? fallbackText : firstUser;
            if (string.IsNullOrWhiteSpace(sourceText)) return;

            await TitleAsync(id, sourceText, ct);
        });

    /// <summary>
    /// Re-titles the session when the latest user message is on a completely
    /// different topic than the one the current title was generated from.
    /// </summary>
    public Task CheckRetitleAsync(string id, CancellationToken ct = default)
        => SafeAsync(async () =>
        {
            var session = _store.GetById(id);
            if (session is null || session.Title == DefaultTitle) return;

            var lastUser = session.Messages.LastOrDefault(m => string.Equals(m.Role, "user", StringComparison.OrdinalIgnoreCase))?.Text;
            if (string.IsNullOrWhiteSpace(lastUser)) return;

            await _titleGate.WaitAsync(ct);
            try
            {
                session = _store.GetById(id);
                if (session?.TitleEmbedding is null) return;
                var embedding = await _embeddings.Value.GenerateAsync(lastUser, ct);
                if (embedding is null) return;

                var similarity = CosineSimilarity(session.TitleEmbedding, embedding);
                if (similarity < TopicChangeThreshold)
                {
                    _logger.LogInformation("[Sessions] Topic change detected (sim={Sim:F2}) for session {Id}, renaming", similarity, id);
                    await TitleAsync(id, lastUser, ct);
                }
            }
            finally
            {
                _titleGate.Release();
            }
        });

    private async Task TitleAsync(string id, string sourceText, CancellationToken ct)
    {
        var title = await GenerateTitleAsync(sourceText, ct);
        float[]? embedding = null;
        try
        {
            embedding = await _embeddings.Value.GenerateAsync(sourceText, ct);
        }
        catch (Exception ex)
        {
            _logger.LogDebug(ex, "[Sessions] Embedding unavailable, topic detection disabled");
        }

        _store.Update(id, s =>
        {
            s.Title = title;
            s.TitleEmbedding = embedding;
        });
    }

    private async Task<string> GenerateTitleAsync(string text, CancellationToken ct)
    {
        var prompt = "Donne un titre très court (2 à 6 mots, en français) résumant le sujet de ce message, sans guillemets ni point final.\n\n" + text;
        try
        {
            var response = await _aiService.Value.ChatAsync(prompt, mode: ModelSelectionMode.Fast, cancellationToken: ct);
            if (response.Success && !string.IsNullOrWhiteSpace(response.Content))
            {
                var title = response.Content.Trim().Trim('"', '\'', '»', '«', '.', ':', ' ').Replace("\n", " ");
                title = System.Text.RegularExpressions.Regex.Replace(title, @"\s+", " ").Trim();
                if (!string.IsNullOrWhiteSpace(title)) return Truncate(title);
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[Sessions] Title generation failed, using fallback");
        }
        return Truncate(text);
    }

    private async Task SafeAsync(Func<Task> action)
    {
        try
        {
            await action();
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[Sessions] Session operation failed");
        }
    }

    private static string Truncate(string text)
    {
        var single = System.Text.RegularExpressions.Regex.Replace(text.Replace("\r", " ").Replace("\n", " "), @"\s+", " ").Trim();
        return single.Length <= 60 ? single : single[..60].TrimEnd() + "…";
    }

    private static float CosineSimilarity(float[] a, float[] b)
    {
        if (a is null || b is null || a.Length == 0 || a.Length != b.Length) return 0f;
        float dot = 0, na = 0, nb = 0;
        for (var i = 0; i < a.Length; i++)
        {
            dot += a[i] * b[i];
            na += a[i] * a[i];
            nb += b[i] * b[i];
        }
        if (na <= 0 || nb <= 0) return 0f;
        return dot / (float)(Math.Sqrt(na) * Math.Sqrt(nb));
    }
}
